### ISSUE TITLE
It does not work correctly for me, I get the 2 visualizations on the same monitor....

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/tchmi-multi-screen#1]
Hello,
It does not work correctly for me, I get the 2 visualizations on the same monitor...
I found this, what do you think?
https://alextomin.wordpress.com/2015/04/10/kiosk-mode-in-windows-chrome-on-multiple-displays/
thank you.

**Comment by benhar-dev** [comment]
As a quick check, just remove the kiosk mode part from your shortcut.  This will keep it in window mode.  Now you can try different versions of ```--window-position="-1024,0"``` to find which direction you need to move it.  I found that on my setup I needed to use a negative number to put it on the left screen and a positive number to put it on the right screen.   You need to have it start with more than 50% of the window on the correct screen so that when it swaps to kiosk then it will expand correctly on to that one. 

Let me know how you get on!

```"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --new-window "http://localhost:1010" --window-size="1024,768" --window-position="-1024,0" --kiosk --user-data-dir="C:/temp/Profiles/2"```

**Comment by benhar-dev** [comment]
Hi @runtimevic is this issue able to be closed?

**Comment by runtimevic** [comment]
> Hi @runtimevic is this issue able to be closed?

yes, closed
